### ISSUE TITLE
请问是否可以出一个部署教程？

### ISSUE THREAD

**Issue by zqq-nuli** [ngcly/MusicStory#2]
因为不是很懂java所以迫切需要一个部署教程，最近在寻找听书项目来听一本开了会员也需要付费的书
后续有空我可以来维护前端UI以及功能
非常感谢

**Comment by ngcly** [comment]
这个只是项目的管理后台以及给前端项目提供相应api的部分。
直接下载当前项目代码，确保本机安装了docker 然后从idea中打开就可以运行了。
至于服务器部署，那这个就需要springboot打包的知识了。

不太理解你上面的听一本开了会员也需要付费的书。 你是打算弄小说网站并实行会员付费机制？
