### ISSUE TITLE
rabbitmq-plugins enable rabbitmq_delayed_message_exchange

### ISSUE THREAD

**Issue by zqq-nuli** [ngcly/MusicStory#3]
请问 rabbitmq-plugins 如何在linxu上安装？
我在安装 rabbitmq-plugins 上遇到了困难
容器内是否有 rabbitmq-plugins 环境？
`rabbitmq-plugins enable rabbitmq_delayed_message_exchange` 是在容器外执行的吗

**Comment by ngcly** [comment]
rabbitmq-plugins 这个是 rabbitmq 的插件。 

docker cp rabbitmq_delayed_message_exchange-3.10.2.ez  rabbitmq:/plugins
这个是在容器外执行的。

rabbitmq-plugins enable rabbitmq_delayed_message_exchange
这个是在容器内执行的，如何进入执行进入容器内。

以上是基于你已经有一定的docker了解，如果对docker不太熟悉，可以百度先了解下 docker一些基本操作。
